name: build and push

on:
  workflow_call:
    inputs:
      imagename:
        required: true
        type: string
    secrets:
      quay_user:
        required: true
      quay_password:
        required: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: git fetch
        run: |
          git fetch
      - name: git checkout
        run: |
          git checkout ${{ github.head_ref }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.quay_user }}
          password: ${{ secrets.quay_password }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: images/${{ inputs.imagename }}
          tags: quay.io/wikimedia-paws-prod/${{ inputs.imagename }}:pr-${{ github.event.number }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
